
/*

Disclaimer of Warranties. The author disclaims to the fullest extent authorized by law any and all other warranties, 
whether express or implied, including, without limitation, any implied warranties of title, non-infringement, quiet enjoyment, 
integration, merchantability or fitness for a particular purpose. Without limitation of the foregoing, the author expressly 
does not warrant that:
(a) the software will meet your requirements or expectations;
(b) the software or the software content] will be free of bugs, errors, viruses or other defects;
(c) any results, output, or data provided through or generated by the software will be accurate, up-to-date, complete or reliable;
(d) the software will be compatible with third party software;
(e) any errors in the software will be corrected.

Under no circumstances shall the author be liable to any user for direct, indirect, incidental, consequential, 
special, or exemplary damages, arising from the software, or user's use or misuse of the software or any other services 
provided by the author. 

Such limitation of liability shall apply whether the damages arise from the use or
misuse of the software or any other services supplied by the author
(including such damages incurred by third parties), or errors of the software.

The software is supplied “as is” and all use is at your own risk.



Author: Michel de Lange

Dunedin, January 2014.

*/
package ac.otago.infoscience.eCRC.client;

import ac.otago.infoscience.eCRC.shared.CancerHistory;

import com.google.gwt.user.client.rpc.RemoteService;
import com.google.gwt.user.client.rpc.RemoteServiceRelativePath;


	@RemoteServiceRelativePath("updatedb")
	
	/**
	 * Send the cancer history for the family to the server.
	 * 
	 * @author michel
	 *
	 * @param history, the family history
	 * @param riskLevel: Calculated risk level
	 * @param erefID: unique ID, provided by the ereferral system. 
	 *
	 */
	public interface UpdateService extends RemoteService {
	 
		
		String updateServer(CancerHistory[] history, short riskLevel, String erefID) throws IllegalArgumentException;
		
	}
