/*

Disclaimer of Warranties. The author disclaims to the fullest extent authorized by law any and all other warranties, 
whether express or implied, including, without limitation, any implied warranties of title, non-infringement, quiet enjoyment, 
integration, merchantability or fitness for a particular purpose. Without limitation of the foregoing, the author expressly 
does not warrant that:
(a) the software will meet your requirements or expectations;
(b) the software or the software content] will be free of bugs, errors, viruses or other defects;
(c) any results, output, or data provided through or generated by the software will be accurate, up-to-date, complete or reliable;
(d) the software will be compatible with third party software;
(e) any errors in the software will be corrected.

Under no circumstances shall the author be liable to any user for direct, indirect, incidental, consequential, 
special, or exemplary damages, arising from the software, or user's use or misuse of the software or any other services 
provided by the author. 

Such limitation of liability shall apply whether the damages arise from the use or
misuse of the software or any other services supplied by the author
(including such damages incurred by third parties), or errors of the software.

The software is supplied “as is” and all use is at your own risk.



Author: Michel de Lange

Dunedin, January 2014.

*/

package ac.otago.infoscience.eCRCpublic.client;



import java.io.Serializable;

public class CancerHistory implements Serializable {
	String name;
	String comment;
	short riskLevel;

	public short getRiskLevel() {
		return riskLevel;
	}

	public void setRiskLevel(short riskLevel) {
		this.riskLevel = riskLevel;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getName() {
		return name;
	}

	public CancerHistory(String nhiNumber, String erefID, short type, String name, 
			boolean colonCancer, short ccAge, boolean multPols,
			boolean otherCancer, short oAge, boolean deceased, short dAge, String comment) {
		super();
		
		this.nhiNumber = nhiNumber;
		this.erefID = erefID;
		this.relationshipType = type;
		this.name = name; 
		this.colonCancer = colonCancer;
		this.ccAge = ccAge;
		this.multPols = multPols;
		this.otherCancer = otherCancer;
		this.oAge = oAge;
		this.deceased = deceased;
		this.dAge = dAge;
		this.comment = comment;
	}

	public CancerHistory() {
		// TODO Auto-generated constructor stub
	}

	
	
	
	
	
	public void setName(String name) {
		this.name = name;
	}

	 

	 

	public boolean isColonCancer() {
		return colonCancer;
	}

	public void setColonCancer(boolean colonCancer) {
		this.colonCancer = colonCancer;
	}

	public int getCcAge() {
		return ccAge;
	}
	

	public void setCcAge(short ccAge) {
		this.ccAge = ccAge;
	}

	public boolean isMultPols() {
		return multPols;
	}

	public void setMultPols(boolean multPols) {
		this.multPols = multPols;
	}

	public boolean isOtherCancer() {
		return otherCancer;
	}

	public void setOtherCancer(boolean otherCancer) {
		this.otherCancer = otherCancer;
	}

	public int getoAge() {
		return oAge;
	}

	public void setoAge(short oAge) {
		this.oAge = oAge;
	}

	public boolean isDeceased() {
		return deceased;
	}

	public void setDeceased(boolean deceased) {
		this.deceased = deceased;
	}

	public int getdAge() {
		return dAge;
	}

	public void setdAge(short dAge) {
		this.dAge = dAge;
	}

	
	String nhiNumber;
	 


	public String getNhiNumber() {
		return nhiNumber;
	}

	public void setNhiNumber(String nhiNumber) {
		this.nhiNumber = nhiNumber;
	}


	 
	boolean colonCancer;
	Short ccAge;
	boolean multPols;
	boolean otherCancer;
	Short oAge;
	boolean deceased;
	Short dAge;
	int relationshipType;
	String erefID; 

	public String getErefID() {
		return erefID;
	}

	public void setErefID(String erefID) {
		this.erefID = erefID;
	}

	public int getRelationshipType() {
		return relationshipType;
	}

	public void setRelationshipType(int relationshipType) {
		this.relationshipType = relationshipType;
	}

	/**
	 * Returns age at which this person was diagnosed with colon cancer
	 * 
	 * @return age, or "" if not so diagnosed. 
	 * 
	 */
	public String getCcAgeString() {
		String result = "";
		if (this.ccAge != null) {
			if (this.ccAge < 0) {
				result = "";
			} else {
				result = this.ccAge.toString();
			}
		} 
		return result;
	}

	/**
	 * Returns age at which this person was diagnosed with other (HNPCC) cancer
	 * 
	 * @return age, or "" if not so diagnosed. 
	 * 
	 */
	public String getoAgeString() {
		String result = "";
		if (this.oAge != null) {
			if (this.oAge < 0) {
				result = "";
			} else {
				result = this.oAge.toString();
			}
		} 
		return result;
	}
	 
	/**
	 * Returns age at which this person died
	 * 
	 * @return age, or "" if not deceased. 
	 * 
	 */
	public String getdAgeString() {
		String result = "";
		if (this.dAge != null) {
			if (this.dAge < 0) {
				result = "";
			} else {
				result = this.dAge.toString();
			}
		} 
		return result;
	}
	
	

	
	

}
