/*

Disclaimer of Warranties. The author disclaims to the fullest extent authorized by law any and all other warranties, 
whether express or implied, including, without limitation, any implied warranties of title, non-infringement, quiet enjoyment, 
integration, merchantability or fitness for a particular purpose. Without limitation of the foregoing, the author expressly 
does not warrant that:
(a) the software will meet your requirements or expectations;
(b) the software or the software content] will be free of bugs, errors, viruses or other defects;
(c) any results, output, or data provided through or generated by the software will be accurate, up-to-date, complete or reliable;
(d) the software will be compatible with third party software;
(e) any errors in the software will be corrected.

Under no circumstances shall the author be liable to any user for direct, indirect, incidental, consequential, 
special, or exemplary damages, arising from the software, or user's use or misuse of the software or any other services 
provided by the author. 

Such limitation of liability shall apply whether the damages arise from the use or
misuse of the software or any other services supplied by the author
(including such damages incurred by third parties), or errors of the software.

The software is supplied “as is” and all use is at your own risk.



Author: Michel de Lange

Dunedin, January 2014.

*/

package ac.otago.infoscience.eCRCpublic.client;

import java.util.logging.Level;
import java.util.logging.Logger;

import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.ClickHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Image;
import com.google.gwt.user.client.ui.VerticalPanel;

/**
 * Panel with the web application header. There are 3 images, with the logos of the 3
 * institutions. Each has got its own link. 
 * 
 * The panel can be wide or narrow, and depending on where you click (and on whether it
 * is wide or narrow), you get a different link, so you go to the web site of the 
 * logo, nearest to where you clicked.
 * 
 * 
 * @author michel
 *
 */
public class HeaderPanel extends VerticalPanel implements ClickHandler {

	Image headerImage;

	String otagoURL = "http://www.otago.ac.nz";
	String otagoTitle = "Otago University";

	String ghnURL = "http://www.guthealthnetwork.com";
	String ghnTitle = "Gut Health Network";

	String mode = Util.HEADER_MODE_WIDE;

	Logger logger = Logger.getLogger("HeaderPanel");
	
	
	HeaderPanel() {
		super();
	}

	HeaderPanel(String mode) {

		super();
		this.mode = mode;
		if (mode.equals(Util.HEADER_MODE_NARROW)) {
			headerImage = new Image("images/header-public-narrow.png");
		} else {
			headerImage = new Image("images/header-public.png");
		}

		this.add(headerImage);
		headerImage.addClickHandler(this);

	}

	@Override
	public void onClick(ClickEvent event) {

		int x = event.getX();
		logger.log(Level.FINEST,"clicked on " + x);
		String url = "http://www.google.com";
		String title = "Google";

		if (mode.equals(Util.HEADER_MODE_WIDE)) {

			if (x < 400) {
				url = otagoURL;
				title = otagoTitle;
			} else  {
				url = ghnURL;
				title = ghnTitle;
			} 
		} else {
			if (x < 400) {
				url = otagoURL;
				title = otagoTitle;
			} else  {
				url = ghnURL;
				title = ghnTitle;
			}  
		}

		Window.open(url, title, "");

	}

}
