/*

Disclaimer of Warranties. The author disclaims to the fullest extent authorized by law any and all other warranties, 
whether express or implied, including, without limitation, any implied warranties of title, non-infringement, quiet enjoyment, 
integration, merchantability or fitness for a particular purpose. Without limitation of the foregoing, the author expressly 
does not warrant that:
(a) the software will meet your requirements or expectations;
(b) the software or the software content] will be free of bugs, errors, viruses or other defects;
(c) any results, output, or data provided through or generated by the software will be accurate, up-to-date, complete or reliable;
(d) the software will be compatible with third party software;
(e) any errors in the software will be corrected.

Under no circumstances shall the author be liable to any user for direct, indirect, incidental, consequential, 
special, or exemplary damages, arising from the software, or user's use or misuse of the software or any other services 
provided by the author. 

Such limitation of liability shall apply whether the damages arise from the use or
misuse of the software or any other services supplied by the author
(including such damages incurred by third parties), or errors of the software.

The software is supplied “as is” and all use is at your own risk.



Author: Michel de Lange

Dunedin, January 2014.

*/

package ac.otago.infoscience.eCRC.server.db;

import java.sql.Timestamp;

public class Relations {
	
	
	
	String id;
	 
	Short relationshipType;
	String erefID;
	String name;
	Short colonCancer;
	Short colonCancerAge;
	Short multiplePolyps;
	Short otherCancer;
	Short otherCancerAge;
	Short deceased;
	Short deceasedAge;
	Short riskLevel;
	Timestamp timest = null;
	String ipAddress;
	public String getIpAddress() {
		return ipAddress;
	}



	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}
	Comment comment;
	
	public String getName() {
		return name;
	}



	public void setName(String name) {
		this.name = name;
	}



	public String getErefID() {
		return erefID;
	}



	public void setErefID(String erefID) {
		this.erefID = erefID;
	}



	
	 


	public Short getRelationshipType() {
		return relationshipType;
	}



	public void setRelationshipType(Short relationshipType) {
		this.relationshipType = relationshipType;
	}



	public Short getColonCancer() {
		return colonCancer;
	}



	public void setColonCancer(Short colonCancer) {
		this.colonCancer = colonCancer;
	}



	public Short getColonCancerAge() {
		return colonCancerAge;
	}



	public void setColonCancerAge(Short colonCancerAge) {
		this.colonCancerAge = colonCancerAge;
	}



	public Short getMultiplePolyps() {
		return multiplePolyps;
	}



	public void setMultiplePolyps(Short multiplePolyps) {
		this.multiplePolyps = multiplePolyps;
	}



	public Short getOtherCancer() {
		return otherCancer;
	}



	public void setOtherCancer(Short otherCancer) {
		this.otherCancer = otherCancer;
	}



	public Short getOtherCancerAge() {
		return otherCancerAge;
	}



	public void setOtherCancerAge(Short otherCancerAge) {
		this.otherCancerAge = otherCancerAge;
	}



	public Short getDeceased() {
		return deceased;
	}



	public void setDeceased(Short deceased) {
		this.deceased = deceased;
	}



	public Short getDeceasedAge() {
		return deceasedAge;
	}



	public void setDeceasedAge(Short deceasedAge) {
		this.deceasedAge = deceasedAge;
	}

public Short getRiskLevel() {
	return riskLevel;
}



public Comment getComment() {
	return comment;
}



public void setComment(Comment comment) {
	this.comment = comment;
}



public void setRiskLevel(Short riskLevel) {
	this.riskLevel = riskLevel;
}
	
	public Relations() {
	
	}
	
	
	
	public Relations(  Short relationshipType,
			String erefID, String name,
			Short colonCancer, Short colonCancerAge, Short multiplePolyps,
			Short otherCancer, Short otherCancerAge, Short deceased,
			Short deceasedAge, Short riskLevel, Timestamp timest, String ipAddress, Comment comment) {
		super();
		 
		this.relationshipType = relationshipType;
		this.erefID = erefID;
		this.name = name;
		this.colonCancer = colonCancer;
		this.colonCancerAge = colonCancerAge;
		this.multiplePolyps = multiplePolyps;
		this.otherCancer = otherCancer;
		this.otherCancerAge = otherCancerAge;
		this.deceased = deceased;
		this.deceasedAge = deceasedAge;
		this.timest = timest;
		this.riskLevel = riskLevel;
		this.ipAddress = ipAddress;
		this.comment = comment;
	}



	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	 
	 
	public Timestamp getTimest() {
		return timest;
	}
	public void setTimest(Timestamp timest) {
		this.timest = timest;
	}

}
